const S = {
  app: {
    maxWidth: 390,
    margin: "0 auto",
    minHeight: "100vh",
    background: "#F8F9FB",
    fontFamily: "'Noto Sans KR', -apple-system, sans-serif",
    position: "relative",
    overflow: "hidden",
  },
  screen: { minHeight: "100vh", display: "flex", flexDirection: "column", background: "#F8F9FB" },
  scrollArea: { flex: 1, overflowY: "auto", paddingBottom: 80 },
  stickyHeader: {
    position: "sticky",
    top: 0,
    zIndex: 20,
    background: "#fff",
  },
  topBar: {
    position: "fixed",
    top: 0,
    left: "50%",
    transform: "translateX(-50%)",
    width: "100%",
    maxWidth: 390,
    background: "#fff",
    borderBottom: "1px solid #E5E7EB",
    zIndex: 300,
    boxSizing: "border-box",
  },
  navBar: {
    position: "fixed",
    bottom: 0,
    left: "50%",
    transform: "translateX(-50%)",
    width: "100%",
    maxWidth: 390,
    background: "#fff",
    borderTop: "1px solid #E5E7EB",
    display: "flex",
    zIndex: 300,
  },
  navItem: (active) => ({
    flex: 1,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    padding: "8px 0 12px",
    cursor: "pointer",
    color: active ? "#2563EB" : "#9CA3AF",
    fontSize: 10,
    fontWeight: active ? 600 : 400,
    gap: 2,
  }),
  card: {
    background: "#fff",
    borderRadius: 16,
    padding: 16,
    marginBottom: 12,
    boxShadow: "0 1px 4px rgba(0,0,0,0.06)",
  },
  btn: (variant = "primary") => ({
    width: "100%",
    padding: "16px 0",
    borderRadius: 14,
    border: "none",
    cursor: "pointer",
    fontSize: 16,
    fontWeight: 600,
    background: variant === "primary" ? "#2563EB" : variant === "outline" ? "#fff" : "#F3F4F6",
    color: variant === "primary" ? "#fff" : variant === "outline" ? "#374151" : "#374151",
    border: variant === "outline" ? "1px solid #E5E7EB" : "none",
  }),
  chip: (selected) => ({
    padding: "8px 14px",
    borderRadius: 20,
    border: selected ? "2px solid #2563EB" : "1px solid #E5E7EB",
    background: selected ? "#EFF6FF" : "#fff",
    color: selected ? "#2563EB" : "#374151",
    fontSize: 14,
    cursor: "pointer",
    fontWeight: selected ? 600 : 400,
  }),
  tag: (color = "#EFF6FF", text = "#2563EB") => ({
    padding: "3px 8px",
    borderRadius: 6,
    background: color,
    color: text,
    fontSize: 11,
    fontWeight: 500,
  }),
  progressBar: (pct, color = "#EF4444") => ({
    height: 6,
    borderRadius: 3,
    background: "#F3F4F6",
    overflow: "hidden",
    position: "relative",
  }),
};

export default S;
